Workbench documents
nimbella/docs pull request #22
Opened 2020-11-30 19:10 UTC by JamieDawson

Here are the workbench documents from https://github.com/nimbella-corp/nimbella-cli/pull/327
Per @joshuaauerbachwatson, request, I have created a new pull request in this repo.

2020-12-02 13:23 UTC, joshuaauerbachwatson commented
Since we are in phase of just getting some missing documents drafted, I'm not going to pick a lot of nits.  All of our documents will likely be wordsmithed and revised going forward.

But, I'd like to see two things corrected before I merge this:

1.  There are broken image links in `workbench-playground-1-intro.md`.   The images should be in the repo and the links should be relative. 
2.  The document `workbench-playground-3-deploy-from-github.md` is misnamed.   It is about a workbench feature but not a playground feature.  

I also note (@JamieDawson, you don't have to fix this prior to merge) that these documents are not connected to the top-level structure in the sidebar.  I will do something about that after the merge.  I believe all of our documents should be connected to "the structure" even though we are pretty likely to revise that structure extensively as the work progresses.

2020-12-02 21:17 UTC, JamieDawson commented
@joshuaauerbachwatson 
> There are broken image links in workbench-playground-1-intro.md. The images should be in the repo and the links should be relative.

Lately, I've just been uploading my images to Flickr and then getting the links from there.  Do you believe we should create an images folder and collectively start adding the images there?

2020-12-02 21:25 UTC, rabbah commented
We should put the images into our repo - is there a reason to use flickr? If not our repo then i would use a nimbella bucket instead, which is also something we control.

2020-12-02 21:26 UTC, joshuaauerbachwatson commented
> Lately, I've just been uploading my images to Flickr and then getting the links from there. Do you believe we should create an images folder and collectively start adding the images there?

There would be no need to create another images folder.   There already is one in `static/img` in this repository.   When @niks3089 moved things over from `newdoc` and established the new structure, he put the images from some of my documents there, alongside some docusaurus ones, so I just assumed we'd continue that convention.

In fact, I am open to other possibilities but the links you have there now don't work (at least they didn't for me).   And I think it _is_ important to be consistent.  So, I believe you should put your images in `static/img` for now and we can separately discuss alternatives as things evolve.

2020-12-02 22:08 UTC, JamieDawson commented
> There are broken image links in workbench-playground-1-intro.md. The images should be in the repo and the links should be relative.

Images added to `static/img`. Thank you for addressing that. I will no longer us Flickr.

> The document workbench-playground-3-deploy-from-github.md is misnamed. It is about a workbench feature but not a playground feature.

Renamed file.

2020-12-08 22:52 UTC, rabbah commented
@JamieDawson please link these docs to the side bar.

2020-12-14 21:26 UTC, JamieDawson commented
1) Documents are linked in the sidebar.
2) A `git rebase` and `git diff --origin workbench-documents` was applied to this repo for completion. 

Document ready for review.

2020-12-14 22:10 UTC, rabbah requested changes

2020-12-14 22:10 UTC, rabbah commented on docs/workbench-activations.md
> +![](https://user-images.githubusercontent.com/16840579/98278991-37434e00-1f4e-11eb-9ad1-3d8356ca37b6.gif)
@JamieDawson this link doesn't work. You need to add the git as a file and make it part of this commit.
Then you can reference it as `./images/<filename>.gif` where filename is the name of the image. Please use a descriptive name.

2020-12-14 22:10 UTC, rabbah commented on docs/workbench-playground-1-intro.md
> +    ![](https://github.com/JamieDawson/docs/blob/workbench-documents/static/img/run_commands_in_playground.gif)
same re link.

2020-12-14 22:10 UTC, rabbah commented on docs/workbench-playground-1-intro.md
> +    ![](https://github.com/JamieDawson/docs/blob/workbench-documents/static/img/playground-test-publish-button-gif.gif)
same re link. Also notice `-gif.gif` redundancy.

2020-12-14 22:10 UTC, rabbah commented on docs/workbench-playground-1-intro.md
> +![](https://github.com/JamieDawson/docs/blob/workbench-documents/static/img/playground_languages.png)
As noted above, add `playground_languages.png` as a file to this PR and commit it, then reference it using a relative link.

2020-12-15 01:43 UTC, JamieDawson commented
All image fixes Rodric requested have been applied.
Pending review.

2020-12-17 02:33 UTC, rabbah commented on docs/workbench-deploy-from-GitHub.md
> +What's nice about the Workbench is that you can deploy your projects that are stored on your GitHub account.
```suggestion
What's nice about the Workbench is that you can deploy your projects directly from your GitHub repositories.
```

2020-12-17 02:33 UTC, rabbah commented on docs/workbench-deploy-from-GitHub.md
> +  "If the project requires building (see [ref](https://github.com/nimbella-corp/nimbella-cli/blob/master/newdoc/building.md)), the build will be run for you in the cloud. This may fail if the build e
The link here in `[ref]` is still wrong.

2020-12-22 21:46 UTC, merged

2020-12-22 21:51 UTC, JamieDawson commented
Hey @rabbah , I believe I made a mistake with this.
After fixing the error "GitHub this branch has conflicts that must be resolved" which was above this post. I clicked the "Squash and merge" button not realizing I could do that on my own. I was under the impression that it would need a 2nd person to ok the merge request.

2020-12-22 21:56 UTC, rabbah commented
It's OK. If there are remaining issues, you can handle them in another PR.
(We haven't enabled checks yet for convenience and you have write privileges and why you can merge your own PRs at this time.)