removed items from footer
nimbella/docs pull request #38
Opened 2021-01-11 20:01 UTC by JamieDawson

There were two boilerplate files in the footer. I removed them and kept accurate Nimbella links.
![footer](https://user-images.githubusercontent.com/16840579/104231865-679ee100-5404-11eb-8a3d-e6104cd28d80.png)

2021-01-11 21:54 UTC, rabbah requested changes
Some of these changes revert previous edits.

2021-01-11 22:23 UTC, JamieDawson reviewed
Reviewing to approve these changes.

2021-01-11 23:25 UTC, JamieDawson commented
I worked with Sam to make the branch updated with his styles. Also added links to bottom of footer for signup and our site.
Pending review.

2021-01-13 20:05 UTC, rabbah commented
I rebased this PR.

2021-01-13 20:14 UTC, merged